config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '',
                     path_names:  { sign_in: 'login', sign_up: 'registro' },
                     controllers: { sessions: 'users/sessions'}
  get '/users/:id', to: 'users#show'
  get '/books', to: 'books#index'
  get '/info', to: 'home#info'

  root 'home#index'
  resources :books
  resources :books do
    resources :pages
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :pages
	belongs_to :user

	validates :title, presence: true, length: {maximum: 144, minimum:3}
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@user = current_user
		@book = Book.all
	end
	
	def new
		@book = Book.new
	end

	def create
	  @book = current_user.books.new book_params 
		if @book.save
			@page = @book.pages.create
			redirect_to edit_book_page_path(@book, @page)
		else
			render 'new'
		end
	end

	def edit
		@book = Book.find(params[:book_id])
		@page = @book.pages.find(params[:id])
		render 'pages/edit'
	end

	def show
		@books = current_user.books.all
		@book = @books.find(params[:id])
		#@page = @book.pages.find(params[:id])

	end

	def destroy
    book = Book.destroy(params[:id])
    redirect_to books_path book.user
  end

		private	
	def book_params
		params.require(:book).permit(:title, :id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	
	def show
		render 'info'
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
require 'json'
	def create
		@book = Book.find(params[:book_id])
		@page = @book.pages.create page_params
		if @page.save && params["commit"] == "+"
			redirect_to new_book_page_path(@book, @page)
		else
			redirect_to book_path(@book)
		end
	end

	def new
		@book = Book.find(params[:book_id])
		@page = @book.pages.create

		redirect_to edit_book_page_path(@book, @page)
	end


	def edit
			@book = Book.find(params[:book_id])
			@page = @book.pages.find(params[:id])
			@next_page = @book.pages.where("id > ?", params[:id]).first
			@prev_page = @book.pages.where("id < ?", params[:id]).first

	end

	def show
			@book = Book.find(params[:book_id])
			@page = @book.pages
			render 'books/edit'

	end

	def update
		@book = Book.find(params[:book_id])
		@next_page = @book.pages.where("id > ?", params[:id]).first
		@prev_page = @book.pages.where("id < ?", params[:id]).first
		@page = @book.pages.find(params[:id]).update_attributes page_params
		if params["commit"] == "+"
			@page = @book.pages.create
			redirect_to edit_book_page_path(@book, @page)
		elsif params["commit"] == "<" && @prev_page
			redirect_to edit_book_page_path(@book, @prev_page)
		elsif params["commit"] == ">" && @next_page
			redirect_to edit_book_page_path(@book, @next_page)
		else
			redirect_to book_path(@book)
		end
	end

	def requireJSON
		source = 'books/pages'
		@info = JSON.parse(JSON.load(source));
	end

		private	
	def page_params
		params.require(:page).permit(:content, :info)
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def create
  	@user=User.new(user_params)
  	if @user.save
  		flash[:success] = "Comienza la aventura!"
  	else
      flash[:error] = "El usuario no existe.¡Registrate!"
  		render 'registro'
  	end
  end

  def show
    redirect_to action: 'index', controller: 'users' unless @user = User.find(params[:id])
   	flash[:error] = "El usuario no existe.¡Registrate!"
    render 'user'
  end

  def update
    render 'edit'
  end
  
  private

  	def user_params
  		params.require(:user).permit(:name, :nickname, :password, :password_confirmation, :email)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_menuObjetos.html.erb
<div id="dib-menu" class="col-xs-3">
	<div class="row">
		<ul class="nav nav-tabs" role="tablist"> 
			<li class="btn-seccion-menu active col-xs-4" role="presentation" >
				<a href="#menu-backgrounds" aria-controls="backgrounds" role="tab" data-toggle="tab">
					<%= image_tag("back-menu.png", alt: "back-menu") %>
				</a>
			</li>
			<li class="btn-seccion-menu col-xs-4" role="presentation" >
				<a href="#menu-characters" aria-controls="characters" role="tab" data-toggle="tab">
				<%= image_tag("char-menu.png", alt: "char-menu") %>
				</a>
			</li>
			<li class="btn-seccion-menu col-xs-4" role="presentation" >
				<a href="#menu-tools" aria-controls="tools" role="tab" data-toggle="tab"> 
				<%= image_tag("tool-menu.png", alt: "tool-menu") %>
				</a>
			</li>
		</ul>
		  <div class="tab-content">
    		<div role="tabpanel" class="tab-pane active" id="menu-backgrounds">
    			<ul>
					<li><div><%= image_tag("back-01.png", alt: "01", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-02.png", alt: "02", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-03.png", alt: "03", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-04.png", alt: "04", class: 'stages') %></div></li>
				</ul>
    		</div>
    		<div role="tabpanel" class="tab-pane" id="menu-characters">
    			<ul>

				<li>
					<div class="draggable tools" data-element="/assets/2.png">
						<%= image_tag("2.png", alt: "boy", :data => {'element' => '/assets/2.png', 'id' => 'character2'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/16.png">
						<%= image_tag("16.png", alt: "mauro", :data => {'element' => '/assets/16.png', 'id' => 'character16'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/15.png">
						<%= image_tag("15.png", alt: "papa", :data => {'element' => '/assets/15.png', 'id' => 'character15'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/3.png">
						<%= image_tag("3.png", alt: "girl", :data => {'element' => '/assets/3.png', 'id' => 'character3'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/14.png">
						<%= image_tag("14.png", alt: "estela", :data => {'element' => '/assets/14.png', 'id' => 'character14'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/7.png">
						<%= image_tag("7.png", alt: "girl", :data => {'element' => '/assets/7.png', 'id' => 'character7'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/1.png">
						<%= image_tag("1.png", alt: "gato", :data => {'element' => '/assets/1.png', 'id' => 'character1'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/11.png">
						<%= image_tag("11.png", alt: "pez", :data => {'element' => '/assets/11.png', 'id' => 'character11'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/12.png">
						<%= image_tag("12.png", alt: "pez", :data => {'element' => '/assets/12.png', 'id' => 'character12'}) %>
					</div>
				</li>
				</ul>
    		</div>
    		<div role="tabpanel" class="tab-pane" id="menu-tools">
    			<ul>
				<li>
					<div class="draggable tools" data-element="/assets/5.png">
						<%= image_tag("5.png", alt: "camara", :data => {'element' => '/assets/5.png', 'id' => 'character5'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/10.png">
						<%= image_tag("10.png", alt: "computer", :data => {'element' => '/assets/10.png', 'id' => 'character10'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/17.png">
						<%= image_tag("17.png", alt: "metro", :data => {'element' => '/assets/17.png', 'id' => 'character17'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/18.png">
						<%= image_tag("18.png", alt: "coche", :data => {'element' => '/assets/18.png', 'id' => 'character18'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/4.png">
						<%= image_tag("4.png", alt: "botas", :data => {'element' => '/assets/4.png', 'id' => 'character4'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/6.png">
						<%= image_tag("6.png", alt: "gorro", :data => {'element' => '/assets/6.png', 'id' => 'character6'}) %>						
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/13.png">
						<%= image_tag("13.png", alt: "gafas", :data => {'element' => '/assets/13.png', 'id' => 'character13'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/8.png">
						<%= image_tag("8.png", alt: "flower", :data => {'element' => '/assets/8.png', 'id' => 'character8'}) %>
					</div>
				</li>
				<li>
					<div class="draggable tools" data-element="/assets/9.png">
						<%= image_tag("9.png", alt: "sombrero", :data => {'element' => '/assets/9.png', 'id' => 'character9'}) %>
					</div>
				</li>
			</ul>
    		</div>
 		</div>
	</div>
</div>

app/views/books/index.html.erb
<h1>La biblioteca de <%= current_user.name %></h1>
<ul class="cuento-thumbnail col-xs-12">
	<% current_user.books.each do |book| %>
	<li class="col-xs-3">
		<p><%= book.title %></p>
		<div class="main-page"></div>
		<div class="book-links">
			<div>
				<%= icon('play-circle-o') %> <%= link_to 'ver', book_path(book) %>
			</div>
			<!-- <div>
				<%= icon('paint-brush') %> <%= link_to 'editar', edit_book_path(book) %>
			</div> -->
			<div>
				<%= icon('trash') %> <%= link_to 'borrar', book_path(book), method: 'delete' %>
			</div>
		</div>
	
	</li>
	<% end %>
</ul>

app/views/books/new.html.erb
<div class="col-xs-8 col-xs-offset-2 add-titulo">
	<h1>Escribe un titulo a tu cuento</h1>
	<%= form_for @book do |f| %>
  		<div class="begin-button">
    		<%= f.text_field :title, autofocus: true %>
  		</div>
  		<%= f.submit "empieza!", class: 'begin-push' %>
	<% end %>
</div>

app/views/books/show.html.erb
<div class="row fullPage">
	<h1 class="col-xs-8 col-xs-offset-2"><%= @book.title %>
		<p>
			<%= link_to 'añadir página', new_book_page_path(@book) %>
		</p>
	</h1>
</div>

<div class="row">
	<!-- <%= icon('chevron-circle-left', '', class: 'col-xs-1') %> -->
	<div class="col-xs-10 col-xs-offset-1 fullPage">
		<% @book.pages.each do |p| %>
	
				<div style="position: relative; background-image: url('<%= JSON.parse(p.info)["bg"] %>'); width:850px; height:422px;" class="stagepreview">
					<% JSON.parse(p.info)["elements"].each do |imagen| %>
						<img src="<%= imagen['img'] %>" style="position: absolute; top: <%= imagen['top'] %>; left: <%= imagen['left'] %>" >
					<% end %>
				</div>

				
				<p class="textoCuento"><%= p.content %></p>
			<div class="editarCuento">
				<%= icon('paint-brush') %> <%= link_to 'editar', edit_book_page_path(@book, p) %>
			</div>
		<% end %>
		
	</div>
	<!-- <%= icon('chevron-circle-right', '', class: 'col-xs-1') %> -->
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<div class="row">
		<div class="col-xs-6   col-xs-offset-3">
			<h2>¡Bienvenid@ <%= current_user.name %>!!</h2>
			<div class="login centrado">							
				<h3>¿Qué te apetece hacer hoy?</h3>
				<div class="tale-links">
					<div>
						<%= icon('paint-brush') %> <%= link_to 'nuevo cuento', new_book_path %>
					</div>
					<div>
						<%= icon('book') %> <%= link_to 'biblioteca', books_path %>
					</div>
				</div>				
			</div>
		</div>
	</div>

<% else %>

	<div id="crea" class="row">
		<div class="col-xs-12 intro">
			<h1>crea</h1>
			<a href="#juega"><%= icon('chevron-circle-down') %></a>
		</div>
	</div>

	<div id="juega" class="row">
		<div class="col-xs-12 intro">
			<h1>juega</h1>
			<a href="#ilustra"><%= icon('chevron-circle-down') %></a>
		</div>
	</div>

	<div id="ilustra" class="row">
		<div class="col-xs-12 intro">
			<%= image_tag("logo-37.png") %>
			<div>
			<div class="welcome-button"><%= link_to 'entra', new_user_session_path %></div>
			<div class="welcome-button"><%= link_to 'registrate', new_user_registration_path %></div>
			<div class="welcome-button"><%= link_to 'explora' %></div>
			</div>
		<a href="#top-nav"><%= icon('chevron-circle-up') %></a>
		</div>
	</div>

<% end %>

app/views/home/info.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1 info-text">
		<h2>ilustra ha sido posible gracias a la paciencia de</h2>
		<p>Harek, Fernando, Raúl, Fran e Iván (entre otros) </p>
		<p>muchas gracias a todos</p>
	</div>
</div>
<div class="row col-xs-offset-3">
	<div class="col-xs-8 info-text">		
		<%= link_to "estelapedrero", 'http://estelapedrero.com' %>
	</div>
</div>

app/views/layouts/_article.html.erb
<div class="row">
	<section>
		<div id="dib-menu" class="col-xs-3">
			<div class="row">
				<div class="col-xs-3 boton">
					<button type="button" class="btn btn-default">
						<%= image_tag("back-menu.png", alt: "back-menu") %>
					</button>
				</div>

				<div class="col-xs-3 boton">
					<button type="button" class="btn btn-default">
						<%= image_tag("char-menu.png", alt: "char-menu") %>
					</button>
				</div>

				<div class="col-xs-3 boton">
					<button type="button" class="btn btn-default">
						<%= image_tag("tool-menu.png", alt: "tool-menu") %>
					</button>
				</div>
			</div>

			<div class="row">
				<ul id="dibujos" >
					<li><div><%= image_tag("back-01.png", alt: "01", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-02.png", alt: "02", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-03.png", alt: "03", class: 'stages') %></div></li>
					<li><div><%= image_tag("back-06.png", alt: "06", class: 'stages') %></div></li>
				</ul>
				<div class="tools-box">

					<div class="col-xs-1 tools-box">

						<div class="draggable tools">
							<%= image_tag("botas.png", alt: "botas") %>
							<div class="delete-button"><p class="delete centrary">x</p></div>
						</div>
						<div class="draggable tools">
						<%= image_tag("gorro.png", alt: "gorro") %>
							<div class="delete-button"><p class="delete centrary">x</p></div>
						</div>
						<div class="draggable tools">
						<%= image_tag("camara.png", alt: "camara") %>
							<div class="delete-button"><p class="delete centrary">x</p></div>
						</div>
					</div>
				</div>
			</div>	
		</div>
		<div id="stage" class="col-xs-8 main-stage">
			<p id="posx" class="coords"></p>
			<p id="posy" class="coords"></p>
		</div>

		<div id="pag-menu" class="col-xs-1">páginas
		</div>	
	</section>
</div>

app/views/layouts/_nav.html.erb
<div class="row">
	<header>
		<div id="header" class="col-xs-12">
			<div class="row">
				<div id="logo" class="col-xs-3">
				<%= link_to image_tag("logo.png"), root_path %>
				</div>
			</div>
			<div class="row">
				<nav>
					<div id="top-nav" class="col-xs-12">
						<% if user_signed_in? %>							
							<div id="book-nav">
								<%= link_to 'mis cuentos', books_path %>	
								<%= link_to 'nuevo cuento', new_book_path %>	
							</div>
						<% end %>
						<div id="info-nav">
							<%= link_to 'info', info_path %>
							<%= link_to 'explora' %>
						</div>
						<div id="user-nav">
							<% if user_signed_in? %>
								<%= link_to current_user.name, edit_user_registration_path  %>
								<%= link_to 'cerrar sesión', destroy_user_session_path, method: 'DELETE' %>
								
							<% else %>
								<%= link_to 'entra', new_user_session_path %>	
								<%= link_to 'regístrate', new_user_registration_path %>
							<% end %>

						</div>	
					</div>
				</nav>
			</div>

		</div>

	</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IlustraC</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Architects+Daughter" />
  <%= javascript_include_tag 'application', defer: :true %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js', defer: :true %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js', defer: :true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
		<%= render "layouts/nav" %>		
		<%= yield %>
	</div>	
</body>
</html>

app/views/pages/edit.html.erb
<section>
	<div class="row">
		<%= render "books/menuObjetos" %>
		<div class="col-xs-8">
			<div class="row">
				<div class="col-xs-12">
					<p class="book-title">
					Título: <%= @book.title %>
					</p>

				</div>
				<div class="stage-margin">
					<div class="wrapper col-xs-12">
						<% unless @page.info.blank? %>
							<div id="stage" class=" main-stage" style='background-image: url("<%= JSON.parse(@page.info)["bg"] %>");'>
								<% JSON.parse(@page.info)["elements"].each do |imagen| %>
								<div class='stage-element' data-src='<%= imagen['img'] %>' style="top: <%= imagen['top'] %>; left: <%= imagen['left'] %>"><i class='delete-button fa fa-times'></i><img src='<%= imagen['img'] %>'></div>
									
								<% end %>
							</div>
						<% else %>
							<div id="stage" class=" main-stage" >
							</div>

						<% end %>
					</div>
					<div class="add-text col-xs-12">
					<%= form_for [@book, @page] do |p| %>
	   					<%= p.text_area :content, placeholder:"Escribe aquí tu texto" %>
					</div>
				</div>
			</div>
		</div>	
					<div id="pag-menu" class="col-xs-1">
						<div class="row botones">
							<%= p.submit "fin", id: 'savebook', class: 'savebutton' %>
	   						<%= p.submit "+", id: 'savepage', class: 'savebutton' %>	
						</div>
						<div class="row botones">
							<% if @prev_page %>
								<%= p.submit "<", id: 'prevpage', class: 'savebutton' %>			
							<% end %>
							<% if @next_page %>
								<%= p.submit ">", id: 'nextpage', class: 'savebutton' %>
							<% end %>
						</div>

					</div>
					<% end %>
	<div id="book_id" data-bookid="<%= @book.id %>"> </div>	
	<div id="page_id" data-pageid="<%= @page.id %>"> </div>				

	</div>					

</section>